"""Training entrypoint generated by canifinetune.

Run:
    python train.py --config config.yaml

This script is intentionally short. It assumes a single GPU and a JSONL
dataset whose rows follow the format documented in dataset_format.md.

Generated for model: sshleifer/tiny-gpt2
Method: lora (LoRA rank=8, target_modules=['c_attn', 'c_proj'])
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import torch
import yaml
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    set_seed,
)


@dataclass
class Config:
    model_id: str = "sshleifer/tiny-gpt2"
    output_dir: str = "output"
    dataset_path: str = "data/sample.jsonl"
    seq_len: int = 128
    micro_batch_size: int = 1
    gradient_accumulation_steps: int = 1
    learning_rate: float = 0.0002
    max_steps: int = 5
    logging_steps: int = 1
    save_steps: int = 100
    seed: int = 42
    gradient_checkpointing: bool = False
    attention_implementation: str = "eager"
    method: str = "lora"
    lora_rank: int = 8
    lora_alpha: int = 32
    lora_dropout: float = 0.05
    target_modules: list = None  # type: ignore[assignment]
    base_dtype: str = "fp32"
    quantization: str = "bf16"
    optimizer: str = "adamw_torch"

    @classmethod
    def from_yaml(cls, path: str | Path) -> "Config":
        data: dict[str, Any] = yaml.safe_load(Path(path).read_text(encoding="utf-8"))
        kwargs = {f: data[f] for f in cls.__dataclass_fields__ if f in data}
        c = cls(**kwargs)
        if c.target_modules is None:
            c.target_modules = list(["c_attn", "c_proj"])
        return c


def _print_env() -> None:
    print("=== environment ===")
    print(f"  python: {sys.version.split()[0]}")
    print(f"  torch:  {torch.__version__}")
    if torch.cuda.is_available():
        idx = torch.cuda.current_device()
        props = torch.cuda.get_device_properties(idx)
        free, total = torch.cuda.mem_get_info()
        print(f"  gpu:    {props.name} ({total/1024**3:.2f} GiB total, {free/1024**3:.2f} GiB free)")
        print(f"  cuda:   {torch.version.cuda}")
        print(f"  bf16:   {torch.cuda.is_bf16_supported()}")
    else:
        print("  gpu:    NONE — training will be CPU-only and very slow.")


def _format_example(tokenizer, instruction: str, input_text: str, output: str, max_len: int) -> dict:
    """Combine instruction + input into a single chat-style prompt."""
    if input_text:
        prompt = f"### Instruction:\n{instruction}\n\n### Input:\n{input_text}\n\n### Response:\n"
    else:
        prompt = f"### Instruction:\n{instruction}\n\n### Response:\n"
    text = prompt + output + tokenizer.eos_token
    enc = tokenizer(text, truncation=True, max_length=max_len, padding="max_length")
    # Mask padding out of the loss. Use attention_mask (not pad_token_id) so a
    # genuine EOS inside the content survives when pad_token == eos_token.
    enc["labels"] = [
        (tok if mask == 1 else -100)
        for tok, mask in zip(enc["input_ids"], enc["attention_mask"])
    ]
    return enc


def load_dataset(path: str, tokenizer, max_len: int) -> Dataset:
    rows: list[dict[str, str]] = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            data = json.loads(line)
            if "messages" in data:
                msgs = data["messages"]
                instruction = next((m["content"] for m in msgs if m["role"] == "user"), "")
                output = next((m["content"] for m in msgs if m["role"] == "assistant"), "")
                input_text = ""
            else:
                instruction = data.get("instruction", "")
                input_text = data.get("input", "")
                output = data.get("output", "")
            rows.append(_format_example(tokenizer, instruction, input_text, output, max_len))
    if not rows:
        raise ValueError(f"No training rows in {path}.")
    return Dataset.from_list(rows)


def build_model_and_tokenizer(cfg: Config):
    tok = AutoTokenizer.from_pretrained(cfg.model_id, use_fast=True)
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token

    if cfg.base_dtype == "bf16":
        torch_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    elif cfg.base_dtype == "fp16":
        torch_dtype = torch.float16
    else:
        torch_dtype = torch.float32

    # transformers 5.0 renamed torch_dtype -> dtype; try new name first.
    model_kwargs: dict[str, Any] = {
        "dtype": torch_dtype,
        "attn_implementation": cfg.attention_implementation,
    }

    if cfg.method == "qlora":
        from transformers import BitsAndBytesConfig
        model_kwargs["quantization_config"] = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_compute_dtype=torch_dtype,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_use_double_quant=(cfg.quantization == "nf4_double_quant"),
        )

    try:
        model = AutoModelForCausalLM.from_pretrained(cfg.model_id, **model_kwargs)
    except TypeError:
        model_kwargs.pop("attn_implementation", None)
        if "dtype" in model_kwargs:
            model_kwargs["torch_dtype"] = model_kwargs.pop("dtype")
        try:
            model = AutoModelForCausalLM.from_pretrained(cfg.model_id, **model_kwargs)
        except TypeError:
            model_kwargs.pop("torch_dtype", None)
            model_kwargs.pop("dtype", None)
            model = AutoModelForCausalLM.from_pretrained(cfg.model_id, **model_kwargs)

    if cfg.method == "qlora":
        from peft import prepare_model_for_kbit_training
        model = prepare_model_for_kbit_training(
            model, use_gradient_checkpointing=cfg.gradient_checkpointing
        )

    if cfg.method != "full":
        from peft import LoraConfig, get_peft_model
        lora_cfg = LoraConfig(
            r=cfg.lora_rank,
            lora_alpha=cfg.lora_alpha,
            lora_dropout=cfg.lora_dropout,
            bias="none",
            target_modules=cfg.target_modules,
            task_type="CAUSAL_LM",
        )
        model = get_peft_model(model, lora_cfg)
        model.print_trainable_parameters()

    if cfg.gradient_checkpointing and hasattr(model, "gradient_checkpointing_enable"):
        try:
            model.gradient_checkpointing_enable()
        except Exception:
            pass

    return model, tok


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="config.yaml")
    parser.add_argument("--max-steps", type=int, default=None)
    parser.add_argument("--dataset", default=None)
    parser.add_argument("--output-dir", default=None)
    args = parser.parse_args()

    cfg = Config.from_yaml(args.config)
    if args.max_steps:
        cfg.max_steps = args.max_steps
    if args.dataset:
        cfg.dataset_path = args.dataset
    if args.output_dir:
        cfg.output_dir = args.output_dir

    set_seed(cfg.seed)
    _print_env()

    try:
        from trl import SFTTrainer  # type: ignore
        has_sft = True
    except Exception:
        has_sft = False

    model, tokenizer = build_model_and_tokenizer(cfg)
    train_ds = load_dataset(cfg.dataset_path, tokenizer, cfg.seq_len)

    train_args = TrainingArguments(
        output_dir=cfg.output_dir,
        per_device_train_batch_size=cfg.micro_batch_size,
        gradient_accumulation_steps=cfg.gradient_accumulation_steps,
        learning_rate=cfg.learning_rate,
        max_steps=cfg.max_steps,
        logging_steps=cfg.logging_steps,
        save_steps=cfg.save_steps,
        save_total_limit=1,
        bf16=(cfg.base_dtype == "bf16" and torch.cuda.is_bf16_supported()),
        fp16=(cfg.base_dtype == "fp16"),
        gradient_checkpointing=cfg.gradient_checkpointing,
        optim=cfg.optimizer,
        report_to=[],
        seed=cfg.seed,
        remove_unused_columns=False,
    )

    if has_sft:
        # SFTTrainer in TRL takes the raw dataset rows; we re-load minimally.
        from datasets import Dataset as _DS
        raw = []
        with open(cfg.dataset_path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    raw.append(json.loads(line))
        sft_ds = _DS.from_list(raw)

        def format_fn(ex):
            if "messages" in ex:
                msgs = ex["messages"]
                user = next((m["content"] for m in msgs if m["role"] == "user"), "")
                assistant = next((m["content"] for m in msgs if m["role"] == "assistant"), "")
                return {"text": f"### Instruction:\n{user}\n\n### Response:\n{assistant}{tokenizer.eos_token}"}
            instr = ex.get("instruction", "")
            inp = ex.get("input", "")
            out = ex.get("output", "")
            if inp:
                text = f"### Instruction:\n{instr}\n\n### Input:\n{inp}\n\n### Response:\n{out}{tokenizer.eos_token}"
            else:
                text = f"### Instruction:\n{instr}\n\n### Response:\n{out}{tokenizer.eos_token}"
            return {"text": text}

        sft_ds = sft_ds.map(format_fn)
        try:
            # Modern TRL (>= ~0.12): SFT-specific args live on SFTConfig and the
            # tokenizer is passed as processing_class.
            from trl import SFTConfig

            sft_args = SFTConfig(
                **train_args.to_dict(),
                max_length=cfg.seq_len,
                dataset_text_field="text",
                packing=False,
            )
            trainer = SFTTrainer(
                model=model,
                args=sft_args,
                train_dataset=sft_ds,
                processing_class=tokenizer,
            )
        except (TypeError, ImportError):
            # Legacy TRL (< ~0.12) keyword API.
            trainer = SFTTrainer(
                model=model,
                args=train_args,
                train_dataset=sft_ds,
                tokenizer=tokenizer,
                max_seq_length=cfg.seq_len,
                dataset_text_field="text",
                packing=False,
            )
    else:
        # Rows are already tokenized, padded, and label-masked by
        # _format_example; default_data_collator just stacks them (a
        # DataCollatorForLanguageModeling would rebuild labels and re-mask
        # every eos when pad_token == eos_token).
        from transformers import Trainer, default_data_collator
        trainer = Trainer(
            model=model,
            args=train_args,
            train_dataset=train_ds,
            data_collator=default_data_collator,
        )

    try:
        trainer.train()
    except torch.cuda.OutOfMemoryError as e:
        print("\n[OOM] CUDA ran out of memory mid-training.")
        print("  Try: smaller micro_batch_size, smaller seq_len, lora_rank, or gradient_checkpointing=True.")
        print(f"  Detail: {e}")
        return 2
    finally:
        # Save whatever we have so the run isn't wasted.
        try:
            os.makedirs(cfg.output_dir, exist_ok=True)
            if hasattr(model, "save_pretrained"):
                model.save_pretrained(cfg.output_dir + "/adapter")
            tokenizer.save_pretrained(cfg.output_dir + "/adapter")
        except Exception as e:
            print(f"[warn] could not save adapter/tokenizer: {e}")

    print("training finished.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
